# Statistical and causal inference for policy change

Most of the rest of this document dives into the details of our statistical decision making. It assumes that the reader has heard of hypothesis tests and
statistical estimators. Here, we explain in very broad terms how tests
and estimators are useful for helping the US federal government improve public policy.

"Evidence-based public policy" can refer to *both* "evidence-as-insight" (the use of previous scientific literature as input to the design of new policies) and "evidence-as-evaluation" (the careful design of studies to learn about how and whether a new policy worked) [@bowers2019better]. Our team aims to help government agencies **design** new policies and **learn** about how those new ideas work. *This document focuses on the learning part of our work.*

How would we know whether and how a new policy worked? In an ideal and
unrealistic case, we would know that a new policy improved the life of a single
person, Jake, if we could compare Jake's decisions *both* under the new policy
*and* under the status quo *at the same moment in time*. If we saw that Jake's
decisions were better under the new policy than under the status quo, we would
say that the new policy *caused* Jake to make better decisions.

Since no one can observe Jake in both situations --- say, making health decisions with and without a new procedure for visiting the doctor --- researchers try to find at least one other person (or more) who represents how Jake would have acted without being exposed to the new policy. @holland:1986a calls this the "fundamental problem of causal inference" and explains more formally when we might believe that other people are a good approximations for how Jake would have acted without the new policy. For example, if access to the new policy is randomized, we can claim that that the two groups are good "counterfactuals" for each other. Our team tends to think about the *causal effects* of a policy in counterfactual terms.

What do statistics have to do with learning about the causal effect of a new
policy idea?  We use randomized experiments to create groups of people who
represent behavior under *both* the new policy and the status quo. In
medical experiments to assess the effectiveness of new treatments, these two
groups tend to be called the "treatment group" and the "control group." Social scientists often use that same language even if we are not really providing a new treatment, but are, instead, offering a new communication or decision-making structure. If we pilot a new policy by offering it to people chosen at random, we can claim that the people chosen and the people not chosen represent or "stand in for" each other. With random assignment of a policy, we can use what we see from one group to learn about what would have happened if the control group had received the new policy instead, or if the treatment group had not.

In any given sample we won't know *exactly* how the treatment group would have behaved if they had been assigned to the control group instead. For example, if we pulled 500 out of 1000 names from a hat and assigned those 500 people to receive treatment, that's just one of many possible sets of 500 people we could have drawn. If we were to do the experiment again, and pulled a different 500 names at random, this second experiment will also have a randomly selected treatment group, but the second 500 people will be at least a little different from the first 500 people. A single experiment offers us *some* information about the effect of treatment, but we need to ask other questions, too, like "How much could our result differ just due to pulling a different 500 people from the hat?" But we also need to answer subtler questions like "What do you mean by 'result'?" or "How do I know that this really is a 'good' result rather than a bad result?"

Questions like those in mind, our team uses statistical theory to produce estimates of the causal effect of a new policy. We also use statistical theory to answer questions like "Could the effect really have been zero?" or "How many people do we need to observe in order to distinguish a positive effect from a zero effect?" The rest of this document presents decisions we have made about the particulars of estimators and tests, as well as other tricky decisions that we have had to confront --- like how we can design experiments using pre-intervention data to make our results as precise as possible. 

For more on the basics of how statistics helps us answer questions about causal
effects, we recommend chapters 1--3 of @gerber_field_2012 (which focuses on
randomized experiments) and the first part of @rosenbaum2017 (which focuses on
both experiments and research designs without randomization). Another good treatment comes from the opening chapters of @angrist2009mostly.




