
# Observational Studies (Policy Evaluations without Randomization)

We can learn about the causal effects of a policy change even if we do not design and implement a randomized control trial. However, when we do not control the policy implementation, then the task of learning about causal effects, the task of causal inference, becomes more difficult. We describe here some of the approaches we have taken to this challenge so far, and also describe some general principles that we would try to follow in the future.

## What justifies statistical inference in an observational study?

Here we describe the "as-if-randomized" approach to statistical inference for causal effects in observational studies. We follow very closely on the work of Paul Rosenbaum in this regards, see for example the discussions in the following textbooks: @rosenbaum2002observational, @rosenbaum2010design, and @rosenbaum2017.

## Approaches to making the case for an as-if-randomized comparison.

### Synthetic Control Methods

### Regression Discontinuity Designs

### Matching

### Regression adjustment


